# Generated by Django 5.2.17 on 2026-10-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_assignment_novelty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('color', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'branches',
                'ordering': ('name',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dni', models.CharField(blank=True, max_length=100, null=True)),
                ('vacation_start', models.DateField(blank=True, null=True)),
                ('vacation_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'people',
                'ordering': ('name', 'id'),
                'managed': False,
            },
        ),
    ]
