# Generated by Django 5.2.17 on 2026-10-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_branch_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentnovelty',
            name='observation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assignmentnovelty',
            name='actual_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignmentnovelty',
            name='kind',
            field=models.CharField(choices=[('late_arrival', 'Llegada tarde'), ('did_not_attend', 'No se presentó'), ('calamity', 'Calamidad')], default='late_arrival', max_length=24),
        ),
    ]
