# Generated by Django 5.2.17 on 2026-10-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_assignmentnovelty_observation_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assignmentnovelty',
            name='unique_assignment_novelty',
        ),
        migrations.AddField(
            model_name='assignmentnovelty',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='assignmentnovelty',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('week_start', 'person_id', 'day'), name='unique_assignment_novelty'),
        ),
    ]
